apiVersion: ecs.services.k8s.aws/v1alpha1
kind: Service
metadata:
  name: mywebsite-ecs-service
spec:
  serviceName: mywebsite-ecs-service
  taskDefinition: mywebsite-task-definition
  cluster: cluster-team-red
  launchType: FARGATE
  desiredCount: 3
  networkConfiguration:
    awsvpcConfiguration:
      assignPublicIP: ENABLED
      securityGroups:
      - sg-00befbceb4e648574
      subnets:
      - subnet-05768c86f85f5b699
